# 计算方法

## Chapter 1 误差分析



In [1]:
def calculate_error(x, y):
    """
    计算两个数的误差

    参数:
    x, y - 待比较的两个数字

    返回:
    两个数字的绝对误差
    """
    return abs(x - y)

def is_within_tolerance(x, y, n):
    """
    判断两个数的差是否小于保留小数点后n位数的容差
    容差定义为 0.5 * 10^(-n)

    参数:
    x, y - 待比较的两个数字
    n - 保留的小数位数

    返回:
    如果两数的误差小于容差则返回 True，否则返回 False
    """
    error = calculate_error(x, y)
    tolerance = 0.5 * 10 ** (-n)
    return error < tolerance
    

## 方程的近似解法

### 二分法

In [2]:
def bisection_method(f, a, b, tol=1e-6, max_iter=100):
    """
    二分法求解方程 f(x)=0 的近似根

    参数:
    f - 目标函数，应满足 f(a)*f(b) < 0
    a, b - 初始区间端点
    tol - 容差（默认1e-6）
    max_iter - 最大迭代次数（默认100）

    返回:
    近似根或者 None（如果初始区间不满足 f(a)*f(b) < 0）
    """
    if f(a) * f(b) >= 0:
        print("错误: 给定区间内可能无根或有多个根。")
        return None

    for _ in range(max_iter):
        mid = (a + b) / 2.0
        f_mid = f(mid)
        if abs(b - a) < tol:
            return mid
        elif f(a) * f_mid < 0:
            b = mid
        else:
            a = mid
    return (a + b) / 2.0

# 示例: 求解 f(x)=x^2-2 在 [0, 2] 区间内的根
def f(x):
    return x**2 - 2

root = bisection_method(f, 0, 2)
print("方程的根是:", root)

方程的根是: 1.4142136573791504


### 迭代法

#### 迭代公式：

$$
x_{n+1}=\varphi\left(x_n\right)
$$




In [ ]:
def iterative_solver(f, x0, tol=1e-6, max_iter=100):
    """
    迭代法求解方程 f(x)=0 的近似根

    参数:
    f - 目标函数
    x0 - 初始猜测值
    tol - 容差（默认1e-6）
    max_iter - 最大迭代次数（默认100）

    返回:
    近似根或者 None（如果未收敛）
    """
    x = x0
    for _ in range(max_iter):
        x_new = f(x)
        if is_within_tolerance(x, x_new, 6):
            return x_new
        x = x_new
    return None

#### 迭代－加速公式
 记 $\tilde{x}_{n+1}=\varphi\left(x_n\right)$ ，由 Lagrange 中值定理有

$$
\tilde{x}_{n+1}-x^*=\varphi^{\prime}(\xi)\left(x_n-x^*\right)
$$

－假定 $\varphi^{\prime}(x)$ 在 $x^*$ 附近变化不大，即 $\varphi^{\prime}(x) \approx q, ~|q|<1$ ，则有

$$
\tilde{x}_{n+1}-x^* \approx q\left(x_n-x^*\right) \quad \Rightarrow \quad x^* \approx \frac{1}{1-q}\left(\tilde{x}_{n+1}-q x_n\right)
$$


重新整理得迭代－加速公式：

$$
\left\{\begin{array}{c}
\tilde{x}_{n+1}=\varphi\left(x_n\right) \\
x_{n+1}=\frac{1}{1-q} \tilde{x}_{n+1}-\frac{q}{1-q} x_n
\end{array}\right.
$$


In [ ]:
def iterative_Acceleration_solver(f, x0, tol=1e-6, max_iter=100):
    """
    迭代加速法求解方程 f(x)=0 的近似根

    参数:
    f - 目标函数
    x0 - 初始猜测值
    tol - 容差（默认1e-6）
    max_iter - 最大迭代次数（默认100）

    返回:
    近似根或者 None（如果未收敛）
    """
    x = x0
    for _ in range(max_iter):
        x_new = f(x)
        q = (f(x)-f(x+tol)) / tol
        if is_within_tolerance(x, x_new, 6):
            return x_new
        x_next = x_new/(1-q) - q*x/(1-q)
        if is_within_tolerance(x, x_next, 6):
            return x_next
        x = x_next
    return None

#### Aitken（埃特金）加速法
记 $\bar{x}_{n+2}=\varphi\left(\tilde{x}_{n+1}\right)$ ，用平均变化率（一阶差商）估计 $q$ ，

$$
q=\varphi^{\prime}(x) \approx \frac{\varphi\left(\tilde{x}_{n+1}\right)-\varphi\left(x_n\right)}{\tilde{x}_{n+1}-x_n}=\frac{\bar{x}_{n+2}-\tilde{x}_{n+1}}{\tilde{x}_{n+1}-x_n}
$$


代入迭代－加速公式后，整理可得 Aitken 加速公式：

$$
\left\{\begin{array}{c}
\tilde{x}_{n+1}=\varphi\left(x_n\right) \\
\bar{x}_{n+2}=\varphi\left(\tilde{x}_{n+1}\right) \\
x_{n+1}=\frac{\bar{x}_{n+2} x_n-\tilde{x}_{n+1}^2}{\bar{x}_{n+2}-2 \tilde{x}_{n+1}+x_n}
\end{array}\right.
$$


In [ ]:
def Atiken_method(f,x0,tol=1e-6,max_iter=100):
    """
    埃德金法加速法求解方程 f(x)=0 的近似根

    参数:
    f - 目标函数
    x0 - 初始猜测值
    tol - 容差（默认1e-6）
    max_iter - 最大迭代次数（默认100）

    返回:
    近似根或者 None（如果未收敛）
    """
    x = x0
    for _ in range(max_iter):
        x_new = f(x)

        if is_within_tolerance(x, x_next, 6):
            return x_new
        x_neww = f(x_new)
        
        x_next = (x*x_neww - x_new*x_new) / (x_neww - 2*x_new + x)
        if is_within_tolerance(x, x_next, 6):
            return x_next
        x = x_next
    return None

## 线性方程组的解法

### 直接法

#### Gauss 顺序消元法

In [ ]:
import numpy as np

def gauss_elimination(A, b):
    """
    使用高斯顺序消元法求解线性方程组 Ax = b

    参数:
    A - 系数矩阵（二维列表或二维 NumPy 数组）
    b - 常数向量（一维列表或 NumPy 数组）

    返回:
    解向量 x（列表形式）
    """
    n = len(A)
    # 将 A 和 b 转换为浮点数矩阵，避免整数除法问题
    A = [list(map(float, row)) for row in A]
    b = list(map(float, b))
    
    # 前向消元
    for i in range(n):
        # 选择主元行
        max_row = max(range(i, n), key=lambda r: abs(A[r][i]))
        if abs(A[max_row][i]) < 1e-12:
            raise ValueError("矩阵奇异或接近奇异，无法求解。")
        A[i], A[max_row] = A[max_row], A[i]
        b[i], b[max_row] = b[max_row], b[i]
        
        # 消元过程
        for j in range(i+1, n):
            factor = A[j][i] / A[i][i]
            b[j] -= factor * b[i]
            for k in range(i, n):
                A[j][k] -= factor * A[i][k]
    
    # 反向代回求解 x
    x = [0] * n
    for i in range(n-1, -1, -1):
        sum_ax = sum(A[i][j] * x[j] for j in range(i+1, n))
        x[i] = (b[i] - sum_ax) / A[i][i]
    return x

# 示例
A = [[2, 1, -1],
     [-3, -1, 2],
     [-2, 1, 2]]
b = [8, -11, -3]
x = gauss_elimination(A, b)
print("线性方程组的解为:", x)



In [3]:
import numpy as np
# 示例增广矩阵（系数与常数在同一矩阵中，最后一列为常数向量）
aug_matrix = np.array([
    [2, 1, -1, 8],
    [-3, -1, 2, -11],
    [-2, 1, 2, -3]
], dtype=float)

# 保留的小数位数
precision = 3

# 创建工作矩阵和记录消元因子的下三角矩阵 L（初始为单位矩阵）
n, m = aug_matrix.shape
A = aug_matrix.copy()
L = np.eye(n)

print("初始增广矩阵:")
print(np.round(A, precision))

# 正向消元，每一行消元完成后打印一次结果
for i in range(n - 1):
    for j in range(i + 1, n):
        factor = A[j, i] / A[i, i]
        factor = round(factor, precision)
        L[j, i] = factor
        for k in range(i, m):
            A[j, k] = round(A[j, k] - factor * A[i, k], precision)
    print(f"\n使用第 {i+1} 行对其他行进行消元后的矩阵:")
    print(np.round(A, precision))

print("\n消元过程中记录的下三角矩阵 L (存储消元因子):")
print(L)

# 反向带回（回代）过程
x = np.zeros(n)
print("\n反向带回过程:")
for i in range(n - 1, -1, -1):
    s = sum(A[i, j] * x[j] for j in range(i + 1, n))
    x[i] = round((A[i, -1] - s) / A[i, i], precision)
    print(f"求解第 {i+1} 个未知数后, 当前解向量: {np.round(x, precision)}")

print("\n线性方程组的解为:")
print(np.round(x, precision))

初始增广矩阵:
[[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]]

使用第 1 行对其他行进行消元后的矩阵:
[[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   2.   1.   5. ]]

使用第 2 行对其他行进行消元后的矩阵:
[[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   0.  -1.   1. ]]

消元过程中记录的下三角矩阵 L (存储消元因子):
[[ 1.   0.   0. ]
 [-1.5  1.   0. ]
 [-1.   4.   1. ]]

反向带回过程:
求解第 3 个未知数后, 当前解向量: [ 0.  0. -1.]
求解第 2 个未知数后, 当前解向量: [ 0.  3. -1.]
求解第 1 个未知数后, 当前解向量: [ 2.  3. -1.]

线性方程组的解为:
[ 2.  3. -1.]


In [1]:
# 矩阵LU分解法求解线性方程组
import numpy as np
from scipy.linalg import lu
def lu_decomposition(A, b):
    """
    使用LU分解法求解线性方程组 Ax = b

    参数:
    A - 系数矩阵（二维列表或二维 NumPy 数组）
    b - 常数向量（一维列表或 NumPy 数组）

    返回:
    解向量 x（列表形式）
    """
    # LU分解
    P, L, U = lu(A)
    
    # 前向替换求解Ly = Pb
    y = np.linalg.solve(L, np.dot(P, b))
    
    # 后向替换求解Ux = y
    x = np.linalg.solve(U, y)
    
    return x.tolist()

In [26]:
import numpy as np

def power_method(A, num_iterations=20, tol=1e-2):
    """
    使用乘幂法计算矩阵 A 的主特征值及对应的特征向量

    参数:
    A - NumPy的二维数组，表示方阵
    num_iterations - 最大迭代次数（默认1000）
    tol - 收敛容差（默认1e-6）

    返回:
    
    迭代次数
    u_1=A*u_k-1
    确定增长速度最快的分量，u_k_j
    u_k_j/u_k-1_j
    """
    n = A.shape[0]
    # 初始猜测向量
    b_k = np.array([1, 0, 0])
    # b_k = b_k / np.linalg.norm(b_k) # 归一化
    
    eigenvalue_old = 0
    for _ in range(num_iterations):
        # 计算 A * b_k
        b_k1 = np.dot(A, b_k)
        # 归一化
        # b_k1_norm = np.linalg.norm(b_k1)
        # b_k1_normalized = b_k1 / b_k1_norm
        
        eigenvalue = b_k1[1] / b_k[1]
        # 使用 np.array2string 格式化数组为字符串
        b_k1_str = np.array2string(b_k1, precision=6, separator=', ')
        print(f"迭代 {_+1:02d}: b_k1: {b_k1_str:<40} Rayleigh 商估计的特征值: {eigenvalue:10.6f}")
        # 判断是否收敛
        if abs(eigenvalue - eigenvalue_old) < tol:
            break
        
        eigenvalue_old = eigenvalue
        b_k = b_k1
        
    return eigenvalue, b_k

# 示例使用
A = np.array([[7,3,-2],
              [3,4,-1],
              [-2,-1,3]])
eigenvalue, eigenvector = power_method(A)
print("主特征值:", eigenvalue)
print("对应的特征向量:", eigenvector)

迭代 01: b_k1: [ 7,  3, -2]                             Rayleigh 商估计的特征值:        inf
迭代 02: b_k1: [ 62,  35, -23]                          Rayleigh 商估计的特征值:  11.666667
迭代 03: b_k1: [ 585,  349, -228]                       Rayleigh 商估计的特征值:   9.971429
迭代 04: b_k1: [ 5598,  3379, -2203]                    Rayleigh 商估计的特征值:   9.681948
迭代 05: b_k1: [ 53729,  32513, -21184]                 Rayleigh 商估计的特征值:   9.622078
迭代 06: b_k1: [ 516010,  312423, -203523]              Rayleigh 商估计的特征值:   9.609172
迭代 07: b_k1: [ 4956385,  3001245, -1955012]           Rayleigh 商估计的特征值:   9.606351
主特征值: 9.606351004887605
对应的特征向量: [ 516010  312423 -203523]


C:\Users\31292\AppData\Local\Temp\ipykernel_21172\4130060198.py:32: RuntimeWarning: divide by zero encountered in scalar divide
  eigenvalue = b_k1[1] / b_k[1]


In [34]:
import numpy as np

def inverse_power_method(A, p, num_iterations=20, tol=1e-5):
    """
    使用反幂法计算矩阵 A 的 p 附近特征值及对应的特征向量

    参数:
    A - NumPy的二维数组，表示方阵
    p - 主特征值的估计值（移位参数）
    num_iterations - 最大迭代次数（默认20）
    tol - 收敛容差（默认1e-5）

    返回:
    最终估计的特征值和对应的特征向量
    """
    n = A.shape[0]  # 矩阵的大小
    I = np.eye(n)
    # 构造移位矩阵（A - pI）
    A_shift = A - p * I
    
    print("移位矩阵 A - pI:")
    print(A_shift)
    # 初始猜测向量
    b_k = np.array([1, 0, 0], dtype=float)
    eigenvalue_old = 0
    
    for itr in range(num_iterations):
        # 解 (A - pI)*b_k1 = b_k
        b_k1 = np.linalg.solve(A_shift, b_k)
        
        # 估计 Rayleigh 商（避免归一化，使用第二分量作为参考）
        # 得到的估计值为 mu，即 1/(b_k1[1]/b_k[1])
        r = b_k1[1] / b_k[1]
        # 反幂法中, 真实特征值 lambda = 1/r + p
        eigen_estimate = 1 / r + p
        
        b_k1_str = np.array2string(b_k1, precision=6, separator=', ')
        print(f"迭代 {itr+1:02d}: b_k1: {b_k1_str:<40} Rayleigh 商估计的特征值: {eigen_estimate:10.6f}")
        
        # 判断是否收敛
        if abs(eigen_estimate - eigenvalue_old) < tol:
            break
        
        eigenvalue_old = eigen_estimate
        b_k = b_k1
    
    return eigen_estimate, b_k

# 示例使用
# 使用全局变量 A（已定义）; 例如 p 选择一个接近我们期望的主特征值估计值
A = np.array([[-12,3,3],
              [3,1,-2],
              [3,-2,7]])

p = -13  # 例如选取 13 作为移位参数
eigenvalue, eigenvector = inverse_power_method(A, p, num_iterations=20, tol=1e-5)
print("反幂法估计的特征值:", eigenvalue)
print("对应的特征向量:", eigenvector)


移位矩阵 A - pI:
[[ 1.  3.  3.]
 [ 3. 14. -2.]
 [ 3. -2. 20.]]
迭代 01: b_k1: [-4.181818,  1.      ,  0.727273]        Rayleigh 商估计的特征值: -13.000000
迭代 02: b_k1: [19.016529, -4.469697, -3.263085]        Rayleigh 商估计的特征值: -13.223729
迭代 03: b_k1: [-86.366516,  20.305326,  14.822356]     Rayleigh 商估计的特征值: -13.220124
迭代 04: b_k1: [392.25429 , -92.22113 , -67.319139]     Rayleigh 商估计的特征值: -13.220181
迭代 05: b_k1: [-1781.516624,   418.844334,   305.74597 ] Rayleigh 商估计的特征值: -13.220180
反幂法估计的特征值: -13.220179962911303
对应的特征向量: [392.2542897  -92.22113003 -67.31913867]


C:\Users\31292\AppData\Local\Temp\ipykernel_21172\3962110006.py:33: RuntimeWarning: divide by zero encountered in scalar divide
  r = b_k1[1] / b_k[1]


In [3]:
import sympy as sp

def newton_divided_diff(x_points, y_points):
    """
    计算牛顿插值的分差表
    返回分差表（二维列表），其中表[0][i]即为多项式的系数a_i
    """
    n = len(x_points)
    # 初始化分差表，第一列为 y 值
    table = [[0 for _ in range(n)] for __ in range(n)]
    for i in range(n):
        table[i][0] = y_points[i]
    # 计算分差
    for j in range(1, n):
        for i in range(n - j):
            table[i][j] = (table[i+1][j-1] - table[i][j-1]) / (x_points[i+j] - x_points[i])
    return table

def newton_polynomial(x_points, table):
    """
    根据分差表构造牛顿插值多项式（使用 sympy 进行符号表达）
    """
    x = sp.symbols('x')
    n = len(x_points)
    poly = table[0][0]
    term = 1
    for i in range(1, n):
        term *= (x - x_points[i-1])
        poly += table[0][i] * term
    return sp.expand(poly)

# 示例数据点
x_points = [1.615, 1.634, 1.702, 1.828,1.921]
y_points = [2.41450,2.46459,2.65271,3.03035,3.34066]

print("数据点:")
print("x:", x_points)
print("y:", y_points)

# 计算分差表
table = newton_divided_diff(x_points, y_points)

print("\n牛顿插值分差表 (每一行只打印有效元素):")
n = len(x_points)
for i in range(n):
    row = [round(table[i][j], 6) for j in range(n - i)]
    print(row)

# 构造牛顿插值多项式
poly = newton_polynomial(x_points, table)
print("\n牛顿插值多项式:")
sp.pprint(poly)

# 代入某一点求插值（例如 x = 3）
eval_point = 1.813
poly_func = sp.lambdify(sp.symbols('x'), poly, "numpy")
result = poly_func(eval_point)
print(f"\n在 x = {eval_point} 处的插值结果为: {result}")

数据点:
x: [1.615, 1.634, 1.702, 1.828, 1.921]
y: [2.4145, 2.46459, 2.65271, 3.03035, 3.34066]

牛顿插值分差表 (每一行只打印有效元素):
[2.4145, 2.636316, 1.496032, -1.441314, 8.824233]
[2.46459, 2.766471, 1.189032, 1.258901]
[2.65271, 2.997143, 1.550337]
[3.03035, 3.336667]
[3.34066]

牛顿插值多项式:
                  4                     3                     2               
8.82423308986889⋅x  - 61.2607899928269⋅x  + 160.577646842901⋅x  - 185.39830696

                         
0759⋅x + 81.0281149292994

在 x = 1.813 处的插值结果为: 2.9833219541190346


In [ ]:
import numpy as np

def forward_difference_table(fx):
    """
    计算前向差商表，并输出中间过程。
    参数:
      fx - 节点处的函数值，数组形式，长度为 n
    返回:
      diff_table - 形状为 (n, n) 的前向差商表，第一列为 fx
    """
    n = len(fx)
    diff_table = np.zeros((n, n))
    diff_table[:, 0] = fx
    print("初始差商表：")
    print(diff_table)
    for j in range(1, n):
        for i in range(n - j):
            diff_table[i, j] = diff_table[i+1, j-1] - diff_table[i, j-1]
        print(f"\n计算第 {j} 阶差商后的表：")
        print(diff_table)
    return diff_table

def newton_forward_interpolation(x_values, fx, x):
    """
    使用牛顿向前插值多项式计算插值结果，并输出中间过程。
    
    参数:
      x_values - 等距节点数组, 如: [x0, x0+h, x0+2h, ...]
      fx       - 节点处的函数值数组
      x        - 待插值的横坐标
    返回:
      插值多项式在 x 处的值
    """
    h = x_values[1] - x_values[0]
    t = (x - x_values[0]) / h
    print(f"计算t值: t = (x - x0) / h = ({x} - {x_values[0]}) / {h} = {t}\n")
    
    diff_table = forward_difference_table(fx)
    n = len(fx)
    interpolation = diff_table[0, 0]
    print(f"初始插值多项式P(x) = {interpolation}")
    t_product = 1.0
    for i in range(1, n):
        t_product *= (t - (i - 1))
        term = t_product * diff_table[0, i] / np.math.factorial(i)
        interpolation += term
        print(f"\n第 {i} 项计算:")
        print(f"  t_product: {t_product}")
        print(f"  差商值: {diff_table[0, i]}")
        print(f"  阶乘: {np.math.factorial(i)}")
        print(f"  本项贡献值: {term}")
        print(f"  当前插值多项式累加结果: {interpolation}")
    return interpolation

# 示例：使用节点以及对应的函数值
x_values = np.array([0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6])
fx = np.array([1, 0.995, 0.98007, 0.95534, 0.92106, 0.87758, 0.82534])
# 求 x = 0.048 处的插值值
x = 0.048
result = newton_forward_interpolation(x_values, fx, x)
print("\n牛顿向前插值代入 x =", x, "的结果为", result)